from enum import Enum


class ErrorCodes(Enum):
    MAX_PAGE_LIMIT = "MAX_PAGE_LIMIT"
    PAGE_CONTENT_TOO_LOW = "PAGE_CONTENT_TOO_LOW"
    FILE_UPLOAD_ERROR = "FILE_UPLOAD_ERROR"
    GENERATE_KEY_ERROR = "GENERATE_KEY_ERROR"
    SERVER_ERROR = "SERVER_ERROR"

